quota_enabled: false

quota:
  request:
    cpu: 4
    memory: 16Gi
  limits:
    cpu: 4
    memory: 16Gi

pvc_limit_enabled: true

pvc_limit_size: 1Ti

## La valeurs peut-Ãªtre egale a Enforce ou Audit
validationFailureAction: Audit


excludedNamespaces:
- "openshift*"
- "infra*"
- etcd-backup
- "kube*"
- "vault*"
- keycloak
- grafana
